AFG:
  # input shapefile downloaded from https://data.humdata.org/dataset/afg-admin-boundaries
  admin:
    directory: afg_admbnda_adm2_agcho_20180522
    language: EN
  pop_co:
    filename: AFG_PopEstimatesOperationalPlanning.xlsx
    province_names:
      Helmand: Hilmand
      Herat: Hirat
      Nooristan: Nuristan
      Sar-e-pul: Sar-e-Pul
      Urozgan: Uruzgan
      Wardak: Maidan Wardak
  kochi:
    # East/South of country
    # from CO: The main focus would be in east as the Kuchis spend winter primarily Kunar, Laghman, Nuristan, Nangahar
    total: 2000000
    adm1:
      - AF15
      - AF07
      - AF16
      - AF06
  ghs:
    column_row_pairs:
      - (23, 4)
      - (23, 5)
      - (24, 4)
      - (24, 5)
  ipc:
    filename: Afghanistan - IPC Analysis 2020-2020.xlsx
  solid_fuels:
    # from https://apps.who.int/gho/data/node.main.135?lang=en
    frac_urban: 28
    frac_rural: 95
  # https://www.who.int/nmh/countries/afg_en.pdf?ua=1
  raised_blood_pressure: 0.23
  # https://www.who.int/nmh/countries/afg_en.pdf?ua=1
  diabetes: 0.08
  covid:
    url: https://proxy.hxlstandard.org/data.csv?dest=data_view&url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1F-AMEDtqK78EA6LYME2oOsWQsgJi4CT3V_G4Uo-47Rg%2Fedit%23gid%3D1539509351
    filename: covid_data.csv
    replace_names:
      Herat: Hirat
      Helmand: Hilmand
      Paktia: Paktya
      Jowzjan: Jawzjan
      Panjshir: Panjsher 
      Urozgan: Uruzgan
      Sar-e Pol: Sar-e-Pul
      Nimruz: Nimroz
      Wardak: Maidan Wardak
      
COD:
  admin:
    # https://data.humdata.org/dataset/drc-administrative-boundaries-levels-0-2
    directory: cod_admbnda_adm2_rgc_20190911
    language: FR

SDN:
  admin:
    # https://data.humdata.org/dataset/sudan-administrative-boundaries-levels-0-2
    directory: sdn_admbnda_adm2_cbs_nic_ssa_20200317
    language: EN

SSD:
  admin:
    # https://data.humdata.org/dataset/south-sudan-administrative-boundaries
    directory: ssd_admbnda_adm2_imwg_nbs_20180817
    language: EN

HTI:
  admin:
    # https://data.humdata.org/dataset/hti-polbndl-adm1-cnigs-zip
    directory: hti_admbnda_adm3_cnigs_20181129
    language: EN
