AFG:
  admin:
    directory: afg_admbnda_adm2_agcho_20180522
    filename: afg_admbnda_adm2_agcho_20180522.shp
  kochi:
    # East/South of country
    # from CO: The main focus would be in east as the Kuchis spend winter primarily Kunar, Laghman, Nuristan, Nangahar
    total: 2000000
    adm1:
      - AF15
      - AF07
      - AF16
      - AF06
