AFG:
  # input shapefile downloaded from https://data.humdata.org/dataset/afg-admin-boundaries
  admin:
    directory: afg_admbnda_adm2_agcho_20180522
    language: EN
  pop_co:
    filename: AFG_PopEstimatesOperationalPlanning.xlsx
    province_names:
      Helmand: Hilmand
      Herat: Hirat
      Nooristan: Nuristan
      Sar-e-pul: Sar-e-Pul
      Urozgan: Uruzgan
      Wardak: Maidan Wardak
  kochi:
    # East/South of country
    # from CO: The main focus would be in east as the Kuchis spend winter primarily Kunar, Laghman, Nuristan, Nangahar
    total: 2000000
    adm1:
      - AF15
      - AF07
      - AF16
      - AF06
  ghs:
    column_row_pairs:
      - (23, 4)
      - (23, 5)
      - (24, 4)
      - (24, 5)
  ipc:
    filename: Afghanistan - IPC Analysis 2020-2020.xlsx
    last_row: 58
    admin_level: 1
    replace_dict:
      Sari Pul: Sar-e-Pul
      Wardak: Maidan Wardak
  solid_fuels:
    # from https://www.who.int/nmh/countries/afg_en.pdf?ua=1
    frac_urban: 0.28
    frac_rural: 0.95
  handwashing_facilities:
    # from https://washdata.org/data/downloads#WLD
    frac_urban: 0.36
    frac_rural: 0.71
  # https://www.who.int/nmh/countries/afg_en.pdf?ua=1
  raised_blood_pressure: 0.23
  # https://www.who.int/nmh/countries/afg_en.pdf?ua=1
  diabetes: 0.08
  # https://vizhub.healthdata.org/tobacco/
  smoking: 0.13
  covid:
    url: https://proxy.hxlstandard.org/data.csv?dest=data_view&url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1F-AMEDtqK78EA6LYME2oOsWQsgJi4CT3V_G4Uo-47Rg%2Fedit%23gid%3D1539509351
    filename: covid_data.csv
    header: 1
    skiprows: 0
    replace_dict:
      Herat: Hirat
      Helmand: Hilmand
      Paktia: Paktya
      Jowzjan: Jawzjan
      Panjshir: Panjsher 
      Urozgan: Uruzgan
      Sar-e Pol: Sar-e-Pul
      Nimruz: Nimroz
      Wardak: Maidan Wardak
    hlx_dict:
      "#affected+infected+cases": "#affected+infected+confirmed+total"
      "#affected+infected+deaths": "#affected+infected+dead+total"

COD:
  admin:
    # https://data.humdata.org/dataset/drc-administrative-boundaries-levels-0-2
    directory: cod_admbnda_adm2_rgc_20190911
    language: FR
  ghs:
    column_row_pairs:
      - (19, 8)
      - (19, 9)
      - (19, 10)
      - (20, 8)
      - (20, 9)
      - (20, 10)
      - (21, 8)
      - (21, 9)
      - (21, 10)
  ipc:
    filename: Congo, DRC - IPC Analysis 2019-2020.xlsx
    last_row: 147
    admin_level: 2
    replace_dict:
      # Admin 2
      Kabeya-kamwanga: Kabeya-Kamwanga
      Katako-kombe: Katako-Kombe
      Malemba-nkulu: Malemba-Nkulu
      Mobayi-mbongo: Mobayi-Mbongo
      # Admin 1
      Bas Uélé: Bas-Uele
      Haut Uélé: Haut-Uele
      Kasai: Kasaï
      Kasai Central: Kasaï-Central
      Kasai Oriental: Kasaï-Oriental
      Kongo Central: Kongo-Central
      Nord Ubangi: Nord-Ubangi
      Sud Ubangi: Sud-Ubangi
      # Country name:
      Congo, DRC:
  solid_fuels:
    # from https://www.who.int/nmh/countries/2018/cod_en.pdf?ua=1
    frac_urban: 0.95
    frac_rural: 0.95
  handwashing_facilities:
    # from https://washdata.org/data/downloads#WLD
    frac_urban: 0.93
    frac_rural: 0.98
  # https://www.who.int/nmh/countries/2018/cod_en.pdf?ua=1
  raised_blood_pressure: 0.22
  # https://www.who.int/nmh/countries/2018/cod_en.pdf?ua=1
  diabetes: 0.04
  # https://vizhub.healthdata.org/tobacco/
  smoking: 0.063  
SDN:
  admin:
    # https://data.humdata.org/dataset/sudan-administrative-boundaries-levels-0-2
    directory: sdn_admbnda_adm2_cbs_nic_ssa_20200317
    language: EN
  ghs:
    column_row_pairs:
      - (20, 6)
      - (20, 7)
      - (21, 6)
      - (21, 7)
  ipc:
    filename: Sudan - IPC Analysis 2019-2020.xlsx
    last_row: 193
    admin_level: 2
    replace_dict:
      # Admin 2:
      Abyei Pca Area: Abyei PCA area
      As Salam - Sd: As Salam - SD
      As Salam - Wk: As Salam - WK
      At Tadamon - Bn: At Tadamon - BN
      Galabat Ash-shargiah: Galabat Ash-Shargiah
      Janub Aj Jazirah: Janub Al Jazirah
      Sharg Aj Jazirah: Sharg Al Jazirah
      # Country name:
      Sudan:
    replace_dict_boundaries:
      North_Kordofan:
        - Ar Rahad
        - Ar Rahad (1)
  solid_fuels:
    # from https://www.who.int/nmh/countries/2018/sdn_en.pdf?ua=1
    frac_urban: 0.59
    frac_rural: 0.59
  handwashing_facilities:
    # from https://washdata.org/data/downloads#WLD
    frac_urban: 0.68
    frac_rural: 0.51
  # Using Chad https://www.who.int/nmh/countries/2018/tcd_en.pdf?ua=1
  # TODO replace with http://www.sho.gov.sd/controller/kn_hub_%20featured.php?sm_id=133&mid=110&lid=1
  raised_blood_pressure: 0.24
  # http://ghdx.healthdata.org/gbd-results-tool?params=gbd-api-2017-permalink/817c42c58dc6cb238e2d1eb03ef8babb
  diabetes: 0.0853
  # https://vizhub.healthdata.org/tobacco/
  smoking: 0.01
SSD:
  admin:
    # https://data.humdata.org/dataset/south-sudan-administrative-boundaries
    directory: ssd_admbnda_adm2_imwg_nbs_20180817
    language: EN
  ghs:
    column_row_pairs:
      - (20, 7)
      - (20, 8)
      - (21, 7)
      - (21, 8)
  ipc:
    filename: South Sudan - IPC Analysis 2020-2020.xlsx
    last_row: 101
    admin_level: 2
    replace_dict:
      # Admin 2
      Canal/pigi: Canal/Pigi
      Luakpiny/nasir: Luakpiny/Nasir
      Wau (rural Only): Wau
      Yei County: Yei
      # Admin 1
      Northern Bahr El Ghazal: Northern Bahr el Ghazal
      Western Bahr El Ghazal: Western Bahr el Ghazal
      # Country
      South Sudan:
  solid_fuels:
    # from https://www.who.int/nmh/countries/2018/ssd_en.pdf?ua=1
    frac_urban: 0.95
    frac_rural: 0.95
  handwashing_facilities:
    # from https://washdata.org/data/downloads#WLD
    frac_urban: 0.93
    frac_rural: 0.98
  # Using Chad https://www.who.int/nmh/countries/2018/tcd_en.pdf?ua=1
  raised_blood_pressure: 0.24
  # http://ghdx.healthdata.org/gbd-results-tool?params=gbd-api-2017-permalink/91c1bfad5bd48ffe4484ccdeca24e066 
  diabetes: 0.0737
  # https://vizhub.healthdata.org/tobacco/
  smoking: 0.064
HTI:
  admin:
    # https://data.humdata.org/dataset/hti-polbndl-adm1-cnigs-zip
    directory: hti_admbnda_adm2_cnigs_20181129
    language: EN
  ipc:
    filename:  Haiti - IPC Analysis 2019-2020.xlsx
    last_row: 69
    admin_level: 2
    replace_dict:
      # Admin 1
      Grand-anse: Grande'Anse
      Nord: North
      Nord-est: North-East
      Nord-ouest: North-West
      Ouest: West
      Sud: South
      Sud-est: South-East
      # Country
      Haiti:
  ghs:
    column_row_pairs:
      - (10, 6)
      - (11, 6)
  solid_fuels:
    # from https://www.who.int/nmh/countries/2018/hti_en.pdf?ua=1
    frac_urban: 0.95
    frac_rural: 0.95
  handwashing_facilities:
    # from https://www.sdg6data.org/country-or-area/Haiti
    frac_urban: 0.77
    frac_rural: 0.77
  # https://www.who.int/nmh/countries/2018/hti_en.pdf?ua=1
  raised_blood_pressure: 0.20
  # https://www.who.int/nmh/countries/2018/hti_en.pdf?ua=1 
  diabetes: 0.07
  # https://vizhub.healthdata.org/tobacco/
  smoking: 0.052
  covid:
    url: https://docs.google.com/spreadsheets/d/e/2PACX-1vTqVOxCSrhEiZ_CRME3Xqhu_DWZv74FvrvOr77rIXOlorClEi0huwVKxXXcVr2hn8pml82tlwmf59UX/pub?output=csv
    filename: covid_data.csv
    replace_dict:
      Herat: Hirat
      Helmand: Hilmand
      Paktia: Paktya
      Jowzjan: Jawzjan
      Panjshir: Panjsher 
      Urozgan: Uruzgan
      Sar-e Pol: Sar-e-Pul
      Nimruz: Nimroz
      Wardak: Maidan Wardak