channels:
  - defaults
  - conda-forge
dependencies:
  - pip=20.2.4
  - numpy==1.19.1
  - geopandas==0.7.0
  - matplotlib==3.2.1
  - requests
  - rasterio==1.1.4
  - xlrd==1.2.0
  - PyYAML==5.3.1
  - networkx==2.4
  - geoplot==0.4.1
  - xarray==0.15.1
  - coloredlogs==14.0

  - pip:
    - topojson==1.0rc9
    - hdx-python-api==4.5.8