channels:
  - defaults
  - conda-forge
dependencies:
  - affine=2.3.0
  - attrs=20.2.0
  - blas=1.0
  - boost-cpp=1.72.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.10.14
  - cairo=1.16.0
  - cartopy=0.18.0
  - certifi=2020.6.20
  - cffi=1.14.3
  - cfitsio=3.470
  - chardet=3.0.4
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.6.0
  - coloredlogs=14.0
  - contextily=1.0.1
  - cryptography=3.1.1
  - curl=7.69.1
  - cycler=0.10.0
  - decorator=4.4.2
  - descartes=1.1.0
  - expat=2.2.10
  - fiona=1.8.13
  - fontconfig=2.13.1
  - freetype=2.10.4
  - freexl=1.0.5
  - gdal=3.0.4
  - geographiclib=1.50
  - geopandas=0.7.0
  - geoplot=0.4.1
  - geopy=2.0.0
  - geos=3.8.0
  - geotiff=1.5.1
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.66.1
  - hdf4=4.2.13
  - hdf5=1.10.5
  - humanfriendly=8.2
  - icu=64.2
  - idna=2.10
  - intel-openmp=2019.4
  - joblib=0.17.0
  - jpeg=9d
  - json-c=0.13.1
  - kealib=1.4.13
  - kiwisolver=1.2.0
  - krb5=1.17.1
  - lcms2=2.11
  - libcurl=7.69.1
  - libcxx=10.0.0
  - libdap4=3.20.6
  - libedit=3.1.20191231
  - libffi=3.3
  - libgdal=3.0.4
  - libgfortran=3.0.1
  - libiconv=1.16
  - libkml=1.3.0
  - libnetcdf=4.7.3
  - libpng=1.6.37
  - libpq=12.2
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.9.0
  - libtiff=4.1.0
  - libwebp=1.0.2
  - libxml2=2.9.10
  - llvm-openmp=10.0.0
  - lz4-c=1.9.2
  - mapclassify=2.3.0
  - matplotlib=3.2.1
  - matplotlib-base=3.2.1
  - mercantile=1.1.6
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - munch=2.5.0
  - ncurses=6.2
  - networkx=2.4
  - numpy=1.19.1
  - numpy-base=1.19.1
  - olefile=0.46
  - openjpeg=2.3.1
  - openssl=1.1.1h
  - owslib=0.20.0
  - pandas=1.1.3
  - pcre=8.44
  - pillow=8.0.0
  - pip=20.2.4
  - pixman=0.38.0
  - poppler=0.67.0
  - poppler-data=0.4.9
  - postgresql=12.2
  - proj=6.3.1
  - pycparser=2.20
  - pyepsg=0.4.0
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyproj=2.6.0
  - pyshp=2.1.2
  - pysocks=1.7.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2020.1
  - pyyaml=5.3.1
  - rasterio=1.1.4
  - readline=8.0
  - requests=2.24.0
  - rtree=0.9.4
  - scikit-learn=0.23.2
  - scipy=1.5.0
  - seaborn=0.11.0
  - setuptools=50.3.0
  - shapely=1.7.1
  - six=1.15.0
  - snuggs=1.4.7
  - sqlite=3.33.0
  - tbb=2020.3
  - threadpoolctl=2.1.0
  - tiledb=1.7.0
  - tk=8.6.10
  - tornado=6.0.4
  - urllib3=1.25.10
  - wheel=0.35.1
  - xarray=0.15.1
  - xerces-c=3.2.2
  - xlrd=1.2.0
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - basicauth==0.4.1
    - bcrypt==3.2.0
    - beautifulsoup4==4.9.3
    - boto3==1.16.1
    - botocore==1.19.1
    - cchardet==2.1.6
    - ckanapi==4.3
    - colorlog==4.4.0
    - dnspython==2.0.0
    - docopt==0.6.2
    - email-validator==1.1.1
    - et-xmlfile==1.0.1
    - hdx-python-api==4.5.8
    - hdx-python-country==2.6.3
    - hdx-python-utilities==2.5.0
    - html5lib==1.1
    - ijson==3.1.2.post0
    - inflect==4.1.0
    - jdcal==1.4.1
    - jmespath==0.10.0
    - jsonlines==1.2.0
    - jsonpath-ng==1.5.2
    - libhxl==4.21.1
    - linear-tsv==1.1.0
    - ndg-httpsclient==0.5.1
    - num2words==0.5.10
    - openpyxl==3.0.5
    - paramiko==2.7.2
    - ply==3.11
    - psycopg2-binary==2.8.6
    - pyaml==20.4.0
    - pyasn1==0.4.8
    - pynacl==1.4.0
    - python-io-wrapper==0.2
    - python-slugify==4.0.1
    - quantulum3==0.7.5
    - ratelimit==2.2.1
    - requests-cache==0.5.2
    - s3transfer==0.3.3
    - soupsieve==2.0.1
    - sqlalchemy==1.3.20
    - sshtunnel==0.1.5
    - tabulator==1.52.4
    - text-unidecode==1.3
    - topojson==1.0rc9
    - unicodecsv==0.14.1
    - unidecode==1.1.1
    - webencodings==0.5.1
    - yamlloader==0.5.5