admin:
  # https://data.humdata.org/dataset/hti-polbndl-adm1-cnigs-zip
  directory: hti_admbnda_adm2_cnigs_20181129
  language: EN
mobility:
  roads:
    url: http://export.hotosm.org/downloads/36004c9d-7b0a-419f-b21f-952d6f728ae9/hotosm_hti_roads_gpkg.zip
  scaling_factor:
    household_size: 4.3
    motor_vehicle_fraction: 0.075
vulnerability:
  ipc:
    filename:  Haiti - IPC Analysis 2019-2020.xlsx
    last_row: 69
    admin_level: 2
    replace_dict:
      # Admin 1
      Grand-anse: Grande'Anse
      Nord: North
      Nord-est: North-East
      Nord-ouest: North-West
      Ouest: West
      Sud: South
      Sud-est: South-East
      # Country
      Haiti:
  ghs:
    column_row_pairs:
      - (10, 6)
      - (11, 6)
  solid_fuels:
    # from https://www.who.int/nmh/countries/2018/hti_en.pdf?ua=1
    frac_urban: 0.95
    frac_rural: 0.95
  handwashing_facilities:
    # from https://www.sdg6data.org/country-or-area/Haiti
    frac_urban: 0.77
    frac_rural: 0.77
  # https://www.who.int/nmh/countries/2018/hti_en.pdf?ua=1
  raised_blood_pressure: 0.20
  # https://www.who.int/nmh/countries/2018/hti_en.pdf?ua=1
  diabetes: 0.07
  # https://vizhub.healthdata.org/tobacco/
  smoking: 0.052
covid:
  url: https://docs.google.com/spreadsheets/d/e/2PACX-1vTqVOxCSrhEiZ_CRME3Xqhu_DWZv74FvrvOr77rIXOlorClEi0huwVKxXXcVr2hn8pml82tlwmf59UX/pub?output=csv
  filename: covid_data.csv
  header: 1
  skiprows: 0
  cases: True
  deaths: True
  cumulative: True
  admin_level: 1
  adm1_name_exp: ADM1_EN
  date_format: "%d-%m-%Y"
  replace_dict:
    Nord: North
    Nord-Ouest: North-West
    Ouest: West
    Nord-Est: North-East
    Sud-Est: South-East
    Sud: South
    Grand Anse: Grande'Anse
contact_matrix:
  country: Haiti
  file_number: 1
