admin:
  directory: irq_admbnda_adm2_cso_20190603
  language: EN
# Settings for the mobility matrix
mobility:
  roads: 
    url: http://export.hotosm.org/downloads/c7df7430-c20e-4016-8039-7f536b0526db/hotosm_irq_roads_gpkg.zip
  scaling_factor:
    household_size: 7.7
    motor_vehicle_fraction: 0.077
# Settings for vulnerability
vulnerabilty:
  ghs:
    column_row_pairs:
      - (21, 4)
      - (21, 5)
      - (22, 4)
      - (22, 5)
  ipc:
    # Name of IPC file
    filename: Congo, DRC - IPC Analysis 2019-2020.xlsx
    # The last row containing data
    last_row: 147
    # The highest admin level in the file (should be 1 or 2)
    admin_level: 2
    # Admin names that need replacement to match the admin region shapefile.
    # You can get these by running the vulnerability script and it will warn of any admin names not found.
    # Should be of the format $ipc_name: $admin_region_name
    replace_dict:
      # Admin 2
      level_2_ipc_name : ~
      # Admin 1
      level_1_ipc_name : ~
      # Country name
      # It's also helpful to replace the country name as it appears in the IPC file with a blank string,
      # otherwise you will get warnings
      country_name:
  solid_fuels:
    frac_urban: 5
    frac_rural: 5
  handwashing_facilities:
    frac_urban: 0.03
    frac_rural: 0.1
  raised_blood_pressure: 0.20
  diabetes: 0.13
  smoking: 0.12
# TODO: covid section
covid:
  url: ~
  filename: ~
  header: ~
  skiprows: ~
  cases: ~
  deaths: ~
  individual_case_data: ~
  cumulative: ~
  admin_level: ~
  federal_state_dict: ~
  adm1_name_exp: ~
  date_format: ~
  replace_dict:
    old_name: ~
  hlx_dict:
    "#old_hxl_name": ~
# Contact matrix settings
contact_matrix:
  # The sheet name of the country to use for the contact matrices
  country: ~
  # Whether the country falls in the first or second set of files (1 or 2)
  file_number: ~
# NPI settings
NPIs:
  # The URL of the published Google sheet with NPIs
  url: ~
