admin:
  # https://data.humdata.org/dataset/somalia-administrative-boundaries
  directory: Som_Admbnda_Adm2_UNDP
  language: EN
mobility:
  roads:
    url: http://export.hotosm.org/downloads/8637e830-985a-46e5-b4d9-988b4426604d/hotosm_som_roads_gpkg.zip
  scaling_factor:
   household_size: 1.0
   motor_vehicle_fraction: 0.2
vulnerability:
  ghs:
    column_row_pairs:
      - (22, 7)
      - (22, 8)
      - (22, 9)
      - (23, 7)
  ipc:
    filename: Somalia - IPC Analysis 2020-2020.xlsx
    last_row: 105
    admin_level: 2
    replace_dict:
      # Admin 2
      # Admin 1
      Juba Dhexe: Middle Juba
      Juba Hoose: Lower Juba
      Shabelle Dhexe: Middle Shabelle
      Shabelle Hoose: Lower Shabelle
      # Country
      Somalia:
  solid_fuels:
    # from https://www.who.int/nmh/countries/2018/som_en.pdf?ua=1
    frac_urban: 0.95
    frac_rural: 0.95
  handwashing_facilities:
    # from https://washdata.org/data/downloads#WLD
    frac_urban: 0.88
    frac_rural: 0.92
  # Using https://www.who.int/nmh/countries/2018/som_en.pdf?ua=1
  raised_blood_pressure: 0.26
  # https://www.who.int/nmh/countries/2018/som_en.pdf?ua=1
  diabetes: 0.05
  # https://vizhub.healthdata.org/tobacco/
  smoking: 0.06
covid:
  url: https://docs.google.com/spreadsheets/d/e/2PACX-1vRTGuZDNylQKqZC7ITpHkLw-7nHvElQNtImJS7kRFXGak664t6jxDjvdVHHWkKPJ7rvwAtj6VGXrQUC/pub?output=csv
  filename: covid_data.csv
  header: 1
  skiprows: 0
  cases: True
  deaths: True
  individual_case_data: False
  cumulative: True
  admin_level: 1
  federal_state_dict:
    # dictionary based on https://bmgf.maps.arcgis.com/apps/opsdashboard/index.html#/d0d9a939c5fa401caa3a7447e72b2017
    'Lower Juba' : "Jubaland"
    'Middle Juba' : "Jubaland"
    'Gedo' : "Jubaland"
    'Bay' : "South West"
    'Bakool' : "South West"
    'Lower Shabelle' : "South West"
    'Banadir' : "Banadir"
    'Hiraan' : "Hir-Shabelle"
    'Middle Shabelle' : "Hir-Shabelle"
    'Mudug' : "Galmudug"
    'Galgaduud' : "Galmudug"
    'Nugaal' : "Puntland"
    'Bari' : "Puntland"
    'Awdal' : "Somaliland"
    'Sool' : "Somaliland"
    'Sanaag' : "Somaliland"
    'Togdheer' : "Somaliland"
    'Woqooyi Galbeed' : "Somaliland"
  adm1_name_exp: ADM1_EN
  date_format: "%m/%d/%Y"
  replace_dict:
    Galmmudug: Galmudug
  hlx_dict:
    '#affected+infected+confirmed': "#affected+infected+confirmed+total"
    '#affected+infected+dead': "#affected+infected+dead+total"
    "#loc+name": "#adm1+name"
contact_matrix:
  country: Kenya
  file_number: 1
NPIs:
  url: https://docs.google.com/spreadsheets/d/e/2PACX-1vQSwkx2eOoeQXEiyp_QjcP71mbIiMTg0Bnyd0pU113XyTP8VoQVxWQjefhM-u8Rsm2uuXZNW2w3dDeH/pub?gid=1334301503&single=true&output=csv

